name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
    - uses: actions/checkout@v2
    - name: docker build csharp
      run: |
        docker build ./c# -t lhyangspg/csharp:1.0.0
    - name: docker build nodejs
      run: |
        docker build -/nodejs -t lhyangspg/nodejs:1.0.0
    - name: docker build python
      run: |
        docker build -/python -t lhyangspg/python:1.0.0
    - name: docker build golang
      run: |
        docker build -/golang -t lhyangspg/golang:1.0.0
